import { AppConfig } from './AppConfig';

export const personSchemaMarkup = {
  '@context': 'https://schema.org/',
  '@type': 'Person',
  name: AppConfig.site_name,
  alternateName: 'Akhil Krishnan',
  url: AppConfig.site_url,
  image: `${AppConfig.site_url}/profile-pic.png`,
  sameAs: [
    'https://facebook.com/akhilgkrishnan9800',
    'https://twitter.com/mrakhilg',
    'https://instagram.com/akhilgkrishnan',
    'https://github.com/akhilgkrishnan',
    'https://stackoverflow.com/users/10321356/akhil-g-krishnan',
    'https://linkedin.com/in/akhilgkrishnan',
    'https://akhilgkrishnan.github.io',
    'https://scholar.google.com/citations?user=RHT03hwAAAAJ&hl=en',
    'https://in.pinterest.com/akhilgkrishnan/',
    'https://www.threads.net/@akhilgkrishnan',
  ],
  jobTitle: 'Senior Software Developer',
  worksFor: {
    '@type': 'Organization',
    name: 'Saeloun Technologies Pvt. Ltd.',
    url: 'https://www.saeloun.com',
  },
  alumniOf: {
    '@type': 'EducationalOrganization',
    name: 'Providence College of Engineering',
  },
  knowsAbout: [
    'Ruby on Rails',
    'React.js',
    'JavaScript',
    'TypeScript',
    'PostgreSQL',
    'Docker',
    'AWS',
    'Git',
    'Full Stack Development',
    'Web Development',
    'Software Engineering',
  ],
  nationality: 'Indian',
  gender: 'Male',
};

export const websiteSchemaMarkup = {
  '@context': 'https://schema.org',
  '@type': 'WebSite',
  name: 'Akhil G Krishnan - Portfolio',
  description: AppConfig.description,
  headline: 'Senior Full Stack Developer | Ruby on Rails & React Expert',
  image: `${AppConfig.site_url}/profile-pic.png`,
  url: AppConfig.site_url,
  author: {
    '@type': 'Person',
    name: 'Akhil G Krishnan',
  },
  publisher: {
    '@type': 'Person',
    name: 'Akhil G Krishnan',
  },
  sameAs: [
    'https://facebook.com/akhilgkrishnan9800',
    'https://twitter.com/mrakhilg',
    'https://instagram.com/akhilgkrishnan',
    'https://github.com/akhilgkrishnan',
    'https://stackoverflow.com/users/10321356/akhil-g-krishnan',
    'https://linkedin.com/in/akhilgkrishnan',
    'https://akhilgkrishnan.github.io',
    'https://scholar.google.com/citations?user=RHT03hwAAAAJ&hl=en',
    'https://in.pinterest.com/akhilgkrishnan/',
    'https://www.threads.net/@akhilgkrishnan',
  ],
};
